export const drivers = [
  {
    id: 1,
    name: "Shaw",
    lastName: "Mosey",
    price: 778.64,
    capacity: 2,
    duration: 36.85,
  },
  {
    id: 2,
    name: "Aubine",
    lastName: "McGeneay",
    price: 9106.86,
    capacity: 7,
    duration: 92.41,
  },
  {
    id: 3,
    name: "Delilah",
    lastName: "Kirby",
    price: 9586.73,
    capacity: 4,
    duration: 62.33,
  },
  {
    id: 4,
    name: "Shadow",
    lastName: "Gibbie",
    price: 5636.13,
    capacity: 5,
    duration: 53.0,
  },
  {
    id: 5,
    name: "Frederich",
    lastName: "Murfill",
    price: 3693.39,
    capacity: 2,
    duration: 40.0,
  },
  {
    id: 6,
    name: "Shaun",
    lastName: "Amsden",
    price: 9993.95,
    capacity: 2,
    duration: 47.62,
  },
  {
    id: 7,
    name: "Dixie",
    lastName: "Hekkert",
    price: 5346.94,
    capacity: 6,
    duration: 20.76,
  },
  {
    id: 8,
    name: "Reidar",
    lastName: "Vasilyonok",
    price: 7741.72,
    capacity: 7,
    duration: 84.41,
  },
  {
    id: 9,
    name: "Gregorio",
    lastName: "Suscens",
    price: 9917.93,
    capacity: 5,
    duration: 59.66,
  },
  {
    id: 10,
    name: "Natty",
    lastName: "Coche",
    price: 2780.36,
    capacity: 3,
    duration: 71.3,
  },
  {
    id: 11,
    name: "Gertruda",
    lastName: "Bimson",
    price: 6857.77,
    capacity: 7,
    duration: 54.25,
  },
  {
    id: 12,
    name: "Shep",
    lastName: "Ivantsov",
    price: 6821.77,
    capacity: 5,
    duration: 90.13,
  },
  {
    id: 13,
    name: "Den",
    lastName: "Allmen",
    price: 649.25,
    capacity: 2,
    duration: 18.21,
  },
];

export const driverInfo = {
  name: "Pedro",
  lastName: "Sánchez",
  calification: "5.0",
  reviews: ["Muy buen conductor", "Muy limpio"],
};
